name: Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version: 1.21.4

      - name: Check out code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - name: Run check
        run: make check

      - name: Lint
        run: make lint
